// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Data.Data;

#nullable disable

namespace Portfolio.Data.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Core.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyContactId");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CompanyContactId = new Guid("33333333-3333-3333-3333-333313333933"),
                            CompanyName = "S&S Activewear"
                        },
                        new
                        {
                            Id = new Guid("10940698-0191-0009-0009-100917666666"),
                            CompanyContactId = new Guid("99999999-9999-9999-9999-999999999999"),
                            CompanyName = "AT&T (through iAOS Solutions)"
                        },
                        new
                        {
                            Id = new Guid("12bbb67b-9b01-1bb2-1bb4-1516b7b8b92b"),
                            CompanyContactId = new Guid("12727278-9221-7772-1727-222277772666"),
                            CompanyName = "TriTech Software Solutions"
                        },
                        new
                        {
                            Id = new Guid("12395698-9901-1912-1914-199917181920"),
                            CompanyContactId = new Guid("12341118-1241-1112-1314-151425522123"),
                            CompanyName = "Logistics Health, Inc."
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01010101-0101-0101-0101-010101010101"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            City = "La Crosse",
                            Email = "",
                            PhoneNumber = "",
                            State = "WI",
                            ZIP = "54601"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333313333933"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            City = "Bolingbrook",
                            Email = "",
                            PhoneNumber = "",
                            State = "IL",
                            ZIP = "60440"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            City = "Schaumburg",
                            Email = "",
                            PhoneNumber = "",
                            State = "IL",
                            ZIP = "60159"
                        },
                        new
                        {
                            Id = new Guid("12727278-9221-7772-1727-222277772666"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            City = "Decorah",
                            Email = "",
                            PhoneNumber = "",
                            State = "IA",
                            ZIP = "52101"
                        },
                        new
                        {
                            Id = new Guid("12341118-1241-1112-1314-151425522123"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            City = "La Crosse",
                            Email = "",
                            PhoneNumber = "",
                            State = "WI",
                            ZIP = "54601"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Models.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DegreeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SchoolContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolContactId");

                    b.ToTable("Education");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            DegreeTitle = "B.S. Software Application Development",
                            EndDate = new DateTime(2015, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolContactId = new Guid("01010101-0101-0101-0101-010101010101"),
                            SchoolName = "Globe University",
                            StartDate = new DateTime(2011, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000028"),
                            Description = "Maintaining and building features for E-commerce and ERP VB.Net WebForm applications",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000029"),
                            Description = "Documenting features and processes for both software team and external departments",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000027"),
                            Description = "Modernizing tech stack to use C# ASP.Net Core and Blazor",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000017"),
                            Description = "Built Windows Service from the ground up for distributing data processing application, including developer documentation",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000018"),
                            Description = "Maintained and added new features for existing ASP.Net MVC application",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            Description = "Updated and maintained two ASP.Net MVC Web application using C#, Typescript, AngularJS, the KendoUI Library, and Entity Framework, based in an Agile Environment",
                            PositionId = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Description = "Updated and maintained WinForm and ASP.Net WebForm applications using VB.Net and SQL in an Agile/Scrum Environment",
                            PositionId = new Guid("12345678-9101-1112-1314-151617181920")
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CompanyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EndDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20"),
                            CompanyId = new Guid("10940698-0191-0009-0009-100917666666"),
                            EndDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f"),
                            CompanyId = new Guid("12bbb67b-9b01-1bb2-1bb4-1516b7b8b92b"),
                            EndDate = new DateTime(2018, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2016, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Associate Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("12345678-9101-1112-1314-151617181920"),
                            CompanyId = new Guid("12395698-9901-1912-1914-199917181920"),
                            EndDate = new DateTime(2015, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2014, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Developer Intern"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Models.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Qualification");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000044"),
                            Description = "VB.Net",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000043"),
                            Description = "ADO.Net",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000042"),
                            Description = "MSSQL",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000041"),
                            Description = "DevExpress",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000040"),
                            Description = "JavaScript",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000039"),
                            Description = "ASP.Net WebForms",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000038"),
                            Description = "CSS/LESS",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000037"),
                            Description = "C#",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000036"),
                            Description = "ASP.Net Core",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000035"),
                            Description = "Blazor",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000034"),
                            Description = "Azure DevOps",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000033"),
                            Description = "Jira",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000032"),
                            Description = "AWS",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000031"),
                            Description = "SEO Development",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000030"),
                            Description = "Scrum Methodology",
                            PositionId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000026"),
                            Description = "C#",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000025"),
                            Description = "ASP.Net Razor",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000024"),
                            Description = "JavaScript",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000023"),
                            Description = "Oracle 11g",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000022"),
                            Description = "PL/SQL",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000021"),
                            Description = "Azure DevOps",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000020"),
                            Description = "Scrum/Agile",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000019"),
                            Description = "MSSQL",
                            PositionId = new Guid("cc3cc6cc-9ccc-1cc2-1cc4-1cccc71ccc20")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000016"),
                            Description = "C#",
                            PositionId = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000015"),
                            Description = "MVC Framework",
                            PositionId = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000014"),
                            Description = "TypeScript",
                            PositionId = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000013"),
                            Description = "AngularJS",
                            PositionId = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000012"),
                            Description = "KendoUI Library",
                            PositionId = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000011"),
                            Description = "Domain-Driven Design",
                            PositionId = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Description = "MSSQL",
                            PositionId = new Guid("1abcdef8-9101-1112-1314-151ab7cd1e2f")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Description = "VB.Net",
                            PositionId = new Guid("12345678-9101-1112-1314-151617181920")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Description = "ADO.Net",
                            PositionId = new Guid("12345678-9101-1112-1314-151617181920")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Description = "DevExpress",
                            PositionId = new Guid("12345678-9101-1112-1314-151617181920")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Description = "MSSQL",
                            PositionId = new Guid("12345678-9101-1112-1314-151617181920")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Description = "WebForms",
                            PositionId = new Guid("12345678-9101-1112-1314-151617181920")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Description = "WinForms",
                            PositionId = new Guid("12345678-9101-1112-1314-151617181920")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Description = "TFS",
                            PositionId = new Guid("12345678-9101-1112-1314-151617181920")
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Models.Company", b =>
                {
                    b.HasOne("Portfolio.Core.Models.Contact", "CompanyContact")
                        .WithMany()
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyContact");
                });

            modelBuilder.Entity("Portfolio.Core.Models.Education", b =>
                {
                    b.HasOne("Portfolio.Core.Models.Contact", "SchoolContact")
                        .WithMany()
                        .HasForeignKey("SchoolContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolContact");
                });

            modelBuilder.Entity("Portfolio.Core.Models.Experience", b =>
                {
                    b.HasOne("Portfolio.Core.Models.Position", null)
                        .WithMany("Experiences")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Models.Position", b =>
                {
                    b.HasOne("Portfolio.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Portfolio.Core.Models.Qualification", b =>
                {
                    b.HasOne("Portfolio.Core.Models.Position", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Models.Position", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
